external_components:
  - source: github://gabe565/esphome-configs@main
    components: [uplift_desk]

uart:
  tx_pin: $tx_pin
  rx_pin: $rx_pin
  baud_rate: 9600

sensor:
  - platform: uplift_desk
    height:
      name: $device_name Height

switch:
  - platform: uplift_desk
    up:
      name: $device_name Move Up
      id: up_switch
    down:
      name: $device_name Move Down
      id: down_switch

button:
  - platform: uplift_desk
    stop:
      name: $device_name Stop
      on_press:
        lambda: |
          id(up_switch).publish_state(false);
          id(down_switch).publish_state(false);
    preset_1:
      name: $device_name Preset 1
    preset_2:
      name: $device_name Preset 2
    preset_3:
      name: $device_name Preset 3
    preset_4:
      name: $device_name Preset 4
    save_preset_1:
      name: $device_name Save Preset 1
    save_preset_2:
      name: $device_name Save Preset 2
    save_preset_3:
      name: $device_name Save Preset 3
    save_preset_4:
      name: $device_name Save Preset 4
    sync:
      name: $device_name Sync
    limit_set_min:
      name: $device_name Limit - Set Min
    limit_set_max:
      name: $device_name Limit - Set Max
    limit_clear:
      name: $device_name Limit - Clear
