status_led:
  pin:
    number: D0
    inverted: true

uart:
  tx_pin: $tx_pin
  rx_pin: $rx_pin
  baud_rate: 9600

uplift_desk:
  id: desk

sensor:
  - platform: uplift_desk
    height:
      name: $device_name Height
      id: height_sensor
    state:
      id: state_sensor

switch:
  # Up
  - platform: template
    name: $device_name Up
    id: move_up_switch
    optimistic: true
    icon: mdi:arrow-up
    turn_on_action:
      - switch.turn_off: move_down_switch
      - while:
          condition:
            lambda: "return true;"
          then:
            - lambda: |
                id(desk).send_cmd_up();
            - delay: 1s
    turn_off_action:
      if:
        condition:
          switch.is_off: move_down_switch
        then:
          lambda: |
            id(desk).send_cmd_stop();

  # Down
  - platform: template
    name: $device_name Down
    id: move_down_switch
    optimistic: true
    icon: mdi:arrow-down
    turn_on_action:
      - switch.turn_off: move_up_switch
      - while:
          condition:
            lambda: "return true;"
          then:
            - lambda: |
                id(desk).send_cmd_down();
            - delay: 1s
    turn_off_action:
      if:
        condition:
          switch.is_off: move_up_switch
        then:
          lambda: |
            id(desk).send_cmd_stop();

  # Save Preset 1
  - platform: template
    name: $device_name Save Preset 1
    id: save_preset_1
    icon: mdi:floppy
    turn_on_action:
      lambda: |
        id(save_preset_1).publish_state(true);
        id(desk).send_cmd_save_preset_1();
        id(save_preset_1).publish_state(false);

  # Save Preset 2
  - platform: template
    name: $device_name Save Preset 2
    id: save_preset_2
    icon: mdi:floppy
    turn_on_action:
      lambda: |
        id(save_preset_2).publish_state(true);
        id(desk).send_cmd_save_preset_2();
        id(save_preset_2).publish_state(false);

  # Save Preset 3
  - platform: template
    name: $device_name Save Preset 3
    id: save_preset_3
    icon: mdi:floppy
    turn_on_action:
      lambda: |
        id(save_preset_3).publish_state(true);
        id(desk).send_cmd_save_preset_3();
        id(save_preset_3).publish_state(false);

  # Save Preset 4
  - platform: template
    name: $device_name Save Preset 4
    id: save_preset_4
    icon: mdi:floppy
    turn_on_action:
      lambda: |
        id(save_preset_4).publish_state(true);
        id(desk).send_cmd_save_preset_4();
        id(save_preset_4).publish_state(false);

  # Preset 1
  - platform: template
    name: $device_name Preset 1
    id: preset_1_switch
    icon: mdi:numeric-1-box
    turn_on_action:
      lambda: |
        id(preset_1_switch).publish_state(true);
        id(desk).send_cmd_preset_1();
        id(preset_1_switch).publish_state(false);

  # Preset 2
  - platform: template
    name: $device_name Preset 2
    id: preset_2_switch
    icon: mdi:numeric-2-box
    turn_on_action:
      lambda: |
        id(preset_2_switch).publish_state(true);
        id(desk).send_cmd_preset_2();
        id(preset_2_switch).publish_state(false);

  # Preset 3
  - platform: template
    name: $device_name Preset 3
    id: preset_3_switch
    icon: mdi:numeric-3-box
    turn_on_action:
      lambda: |
        id(preset_3_switch).publish_state(true);
        id(desk).send_cmd_preset_3();
        id(preset_3_switch).publish_state(false);

  # Preset 4
  - platform: template
    name: $device_name Preset 4
    id: preset_4_switch
    icon: mdi:numeric-4-box
    turn_on_action:
      lambda: |
        id(preset_4_switch).publish_state(true);
        id(desk).send_cmd_preset_4();
        id(preset_4_switch).publish_state(false);

  # Manual Sync
  - platform: template
    name: $device_name Sync
    id: sync_switch
    icon: mdi:sync
    turn_on_action:
      lambda: |
        id(sync_switch).publish_state(true);
        id(desk).send_cmd_sync();
        id(sync_switch).publish_state(false);
