esphome:
  name: $device_id

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: wifi_signal
    name: $device_name RSSI
    update_interval: 5min
    filters:
      - median:
          window_size: 5

api:
  password: $api_password

logger:

ota:
  password: $ota_password

binary_sensor:
  - platform: status
    name: $device_name Status

